"""
B站 Cookie 刷新脚本
Playwright 打开 B站首页 → 等待扫码登录 → 导出 cookies.txt（Netscape 格式）
"""

import asyncio
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from playwright.async_api import async_playwright

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_DIR = SCRIPT_DIR.parent
COOKIES_PATH = PROJECT_DIR / "cookies.txt"
BILIBILI_URL = "https://www.bilibili.com/"

REQUIRED_COOKIES = {"DedeUserID", "SESSDATA", "bili_jct"}
LOGIN_TIMEOUT = 300
POLL_INTERVAL = 2


def _cookie_header():
    now = datetime.now(timezone.utc).timestamp()
    return f"# Netscape HTTP Cookie File\n# Generated by bilibili refresh_cookies.py\n# {datetime.now():%Y-%m-%d %H:%M:%S}\n\n"


def _cookie_line(cookie):
    domain = cookie.get("domain", ".bilibili.com")
    flag = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path", "/")
    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
    expires = str(cookie.get("expires", -1))
    name = cookie["name"]
    value = cookie.get("value", "")
    return f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"


async def main():
    print("=" * 52)
    print("  B站 Cookie 刷新脚本")
    print(f"  登录超时: {LOGIN_TIMEOUT}s | 检测间隔: {POLL_INTERVAL}s")
    print("=" * 52)
    print()

    async with async_playwright() as p:
        print("[步骤1] 启动 Chrome 浏览器...")
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()

        try:
            print(f"[步骤2] 正在访问 {BILIBILI_URL}")
            try:
                await page.goto(BILIBILI_URL, wait_until="domcontentloaded", timeout=60_000)
            except Exception:
                print("[WARN] 页面加载超时，尝试继续...")

            print(f"[步骤3] 请在浏览器中完成扫码登录")
            print(f"        超时: {LOGIN_TIMEOUT}s | 所需 Cookie: {REQUIRED_COOKIES}")

            logged_in = False
            for i in range(LOGIN_TIMEOUT // POLL_INTERVAL):
                await asyncio.sleep(POLL_INTERVAL)
                cookies = await context.cookies()
                cookie_names = {c["name"] for c in cookies}
                if REQUIRED_COOKIES.issubset(cookie_names):
                    logged_in = True
                    elapsed = (i + 1) * POLL_INTERVAL
                    print(f"\n[步骤3] ✓ 检测到登录 ({elapsed}s)")
                    break
                if i % 5 == 0:
                    current = REQUIRED_COOKIES & cookie_names
                    if current:
                        print(f"  ... 已有: {current}")

            if not logged_in:
                print("\n[FAIL] 登录超时，未检测到完整 Cookie")
                await browser.close()
                sys.exit(1)

            print("[步骤4] 正在导出 cookies.txt (Netscape 格式)...")
            all_cookies = await context.cookies()

            with open(COOKIES_PATH, "w", encoding="utf-8") as f:
                f.write(_cookie_header())
                for c in all_cookies:
                    f.write(_cookie_line(c))

            cookie_names = [c["name"] for c in all_cookies]
            print(f"[步骤4] ✓ 已导出 {len(all_cookies)} 个 Cookie")

            print()
            print("=" * 52)
            print(f"  ✓ 登录成功，Cookie 已保存")
            print(f"  核心 Cookie: {REQUIRED_COOKIES & set(cookie_names)}")
            print(f"  文件: {COOKIES_PATH}")
            print("=" * 52)

        except Exception as e:
            print(f"\n[ERROR] 脚本异常: {e}")
            traceback.print_exc()
            sys.exit(1)
        finally:
            await browser.close()


if __name__ == "__main__":
    asyncio.run(main())